In [140]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [95]:
dfs = pd.read_csv("Titanic-Dataset.csv")
df = dfs.copy()
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<!-- issue -->
age have to be in int not in float

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [110]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [109]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [128]:
avg_age = df['Age'].median()
df['Age'] = df['Age'].fillna(avg_age).round().astype(int)
df['Age'].dtype
df[['Name', 'Age']].head()
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
424,425,0,3,"Rosblom, Mr. Viktor Richard",male,18,1,1,370129,20.2125,S
129,130,0,3,"Ekstrom, Mr. Johan",male,45,0,0,347061,6.9750,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25,0,0,LINE,0.0000,S
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,C
73,74,0,3,"Chronopoulos, Mr. Apostolos",male,26,1,0,2680,14.4542,C

In [104]:
df['Embarked'].ffill(inplace=True)

In [108]:
df.drop(columns='Cabin',inplace=True)

In [129]:
df['PassengerId'].duplicated().sum()

np.int64(0)

In [161]:
passenger_id = df['PassengerId'].count()
display(passenger_id)
survived = df[df['Survived'] == 1]['Survived'].count()
display(survived)

df['Survived'].value_counts()

np.int64(891)

np.int64(342)

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
# 3rd class mean poor people 
# 2nd class mean middle class people
# 1st class mean rich people

In [160]:
c1 = df['Pclass'].value_counts()
c1

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [162]:
# by choosing praticular port we can identify which people is curious about the ship 

df_port = df[['Embarked']].value_counts()
df_port

Embarked
S           644
C           169
Q            78
Name: count, dtype: int64