In [134]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [135]:
dfs = pd.read_csv("Titanic-Dataset.csv")
df = dfs.copy()
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

<!-- issue -->
age have to be in int not in float

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [137]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [138]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [139]:
avg_age = df['Age'].median()
df['Age'] = df['Age'].fillna(avg_age).round().astype(int)
df['Age'].dtype
df[['Name', 'Age']].head()
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
83,84,0,1,"Carrau, Mr. Francisco M",male,28,0,0,113059,47.1000,NaN,S
212,213,0,3,"Perkin, Mr. John Henry",male,22,0,0,A/5 21174,7.2500,NaN,S
804,805,1,3,"Hedman, Mr. Oskar Arvid",male,27,0,0,347089,6.9750,NaN,S
645,646,1,1,"Harper, Mr. Henry Sleeper",male,48,1,0,PC 17572,76.7292,D33,C
363,364,0,3,"Asim, Mr. Adola",male,35,0,0,SOTON/O.Q. 3101310,7.0500,NaN,S

In [140]:
df['Embarked'].ffill(inplace=True)

In [141]:
df.drop(columns='Cabin',inplace=True)

In [142]:
df['PassengerId'].duplicated().sum()

np.int64(0)

In [143]:
passenger_id = df['PassengerId'].count()
display(passenger_id)
survived = df[df['Survived'] == 1]['Survived'].count()
display(survived)

df['Survived'].value_counts()

np.int64(891)

np.int64(342)

Survived
0    549
1    342
Name: count, dtype: int64

In [144]:
# 3rd class mean poor people 
# 2nd class mean middle class people
# 1st class mean rich people

In [145]:
c1 = df['Pclass'].value_counts()
c1

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [146]:
# by choosing praticular port we can identify which people is curious about the ship 

df_port = df[['Embarked']].value_counts()
df_port

Embarked
S           644
C           169
Q            78
Name: count, dtype: int64

In [147]:
df['Family_size'] = df['SibSp']+df['Parch']

In [148]:
df.drop(columns=['SibSp','Parch','Ticket'],inplace= True)

In [149]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,Fare,Embarked,Family_size
181,182,0,2,"Pernot, Mr. Rene",male,28,15.05,C,0

In [150]:
df['Title']=df['Name'].str.split(", ",expand=True)[1].str.split(".",expand=True)[0]
df['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [151]:
df['Title'] = df['Title'].replace(['Lady', 'the Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
df['Title'] = df['Title'].replace('Mlle', 'Miss')
df['Title'] = df['Title'].replace('Ms', 'Miss')
df['Title'] = df['Title'].replace('Mme', 'Mrs')

In [152]:
df['Title'].value_counts()

Title
Mr        517
Miss      185
Mrs       126
Master     40
Rare       23
Name: count, dtype: int64

In [153]:
df.drop(columns='Name',inplace=True)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          891 non-null    int64
 5   Fare         891 non-null    float64
 6   Embarked     891 non-null    object
 7   Family_size  891 non-null    int64
 8   Title        891 non-null    object
dtypes: float64(1), int64(5), object(3)
memory usage: 62.8+ KB

In [ ]:
# def family_size(number):
#     number  = int(number)
#     if number==1:
#         return "Alone"
#     elif number>1 and number <5:
#         return "Small"
#     else:
#         return "Large"

In [ ]:
# df['Family_size'].isna().sum()
# # df['Family_size']=df['Family_size'].apply(family_size)

np.int64(0)